services:
  postgres:
    image: postgres:latest
    container_name: nexign
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nexign
    restart: always
    volumes:
      - /var/lib/postgresql/data